[package]
name = "stepflow-test-util"
description = "Test utilities for StepFlow"
homepage = "https://stepflow.dev"
license = "Apache-2.0"
version = "0.0.1"
authors = ["John Wana <john@wana.us>"]
edition = "2018"
