[package]
name = "stepflow-test-util"
version = "0.0.1"
authors = ["John Wana <john@wana.us>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
