[package]
name = "stepflow-base"
version = "0.0.1"
authors = ["John Wana <john@wana.us>"]
edition = "2018"
publish = false


[features]
test = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
stepflow-test-util = { path = "../stepflow-test-util" }